### ISSUE TITLE
docker exec -it yunzai-bot node app 时发生 YAMLParseError

### ISSUE THREAD

**Issue by hypergraphUniverse** [SirlyDreamer/Yunzai-Bot#15]
## Docker信息
```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
## 运行代码
```
sudo docker exec -it yunzai-bot node app
/app/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:170
                const error = new errors.YAMLParseError(getErrorPos(token), 'UNEXPECTED_TOKEN', msg);
                              ^

YAMLParseError: Unexpected scalar token in YAML stream: "pwd" at line 6, column 1:


pwd: (这个地方就不展示了，密码里面有特殊字符)
^^^

    at Composer.next (/app/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:170:31)
    at next (<anonymous>)
    at Composer.compose (/app/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:131:25)
    at compose.next (<anonymous>)
    at parseDocument (/app/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/public-api.js:45:16)
    at Object.parse (/app/Yunzai-Bot/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/public-api.js:67:17)
    at Cfg.getYaml (file:///app/Yunzai-Bot/lib/config/config.js:117:22)
    at Cfg.getConfig (file:///app/Yunzai-Bot/lib/config/config.js:104:17)
    at get qq [as qq] (file:///app/Yunzai-Bot/lib/config/config.js:30:24)
    at createQQ (file:///app/Yunzai-Bot/lib/config/qq.js:12:11) {
  code: 'UNEXPECTED_TOKEN',
  pos: [ 54, 57 ],
  linePos: [ { line: 6, col: 1 }, { line: 6, col: 4 } ]
}

Node.js v18.8.0
```

**Comment by hypergraphUniverse** [comment]
我发现了，那就是实际上是因为前面qq一栏和前面没有空格

(错误)
```
qq:123456
```

(正确)
```
qq: 123456
```
