### ISSUE TITLE
关于重启的疑问

### ISSUE THREAD

**Issue by shuangxunian** [SirlyDreamer/Yunzai-Bot#31]
我在centos8中，执行`sudo docker exec -it yunzai-bot node app`后已经可以正常交互，但是我按快捷键 Ctrl+C 退出，然后执行`sudo docker compose restar`后，一直启动不起来，进到容器里面看到一直在下依赖，下完后又重新下载，请问这个问题应该如何解决

**Comment by SirlyDreamer** [comment]
请问能否提供日志？查看方式：`docker logs yunzai-bot`

**Comment by shuangxunian** [comment]
您好，一直是如下，一遍运行完之后又会重头运行
```
 ================ 
 [信息]  更新 py-plugin 运行依赖  
 ================ 

Progress: resolved 0, reused 1, downloaded 0, added 0
Progress: resolved 186, reused 186, downloaded 0, added 0
Progress: resolved 187, reused 187, downloaded 0, added 0
 WARN  GET https://registry.npmjs.org/@pm2%2Fpm2-version-check error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/fsevents error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
Progress: resolved 188, reused 187, downloaded 0, added 0
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Progress: resolved 289, reused 288, downloaded 0, added 0
Already up to date

Progress: resolved 289, reused 288, downloaded 0, added 0, done
Updating dependencies
Resolving dependencies...

No dependencies to install or update
Traceback (most recent call last):
  File "/app/Yunzai-Bot/plugins/py-plugin/./install/requirements.py", line 47, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/Yunzai-Bot/plugins/py-plugin/./install/requirements.py", line 28, in main
    for app in (__path__.parent / "apps").iterdir():
  File "/usr/lib/python3.9/pathlib.py", line 1149, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/app/Yunzai-Bot/plugins/py-plugin/apps'

 ================ 
 [信息]  拉取 Yunzai-Bot 更新  
 ================ 

From https://gitee.com/Le-niao/Yunzai-Bot
 * branch            main       -> FETCH_HEAD
Already up to date.

 ================ 
 [信息]  更新 Yunzai-Bot 运行依赖  
 ================ 

Lockfile is up to date, resolution step is skipped
Packages: -136
--------------------------------------------------------------------------------

devDependencies:
- eslint 8.18.0
- eslint-config-standard 17.0.0
- eslint-plugin-import 2.26.0
- eslint-plugin-n 15.2.3
- eslint-plugin-promise 6.0.0
- express 4.18.1
- express-art-template 1.0.1


 ================ 
 [版本]  Yunzai-Bot 版本信息  
 ================ 

9709a85 - Le-niao, 2 hours ago (Mon Nov 21 08:46:24 2022 +0800) : 格式化代码
 ================ 
 [信息]  拉取 喵喵插件 更新  
 ================ 

From https://gitee.com/yoimiya-kokomi/miao-plugin
 * branch            master     -> FETCH_HEAD
Already up to date.

 ================ 
 [信息]  更新 喵喵插件 运行依赖  
 ================ 

Progress: resolved 0, reused 1, downloaded 0, added 0
Progress: resolved 438, reused 438, downloaded 0, added 0
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Progress: resolved 521, reused 520, downloaded 0, added 0
```

**Comment by SirlyDreamer** [comment]
似乎是因为py插件没有完整安装，请检查一下

**Comment by shuangxunian** [comment]
请问这个有什么方法吗

**Comment by shuangxunian** [comment]
而且请问 如果我差价有问题的话 为什么可以`sudo docker exec -it yunzai-bot node app`启动呢

**Comment by shuangxunian** [comment]
您好 我解决了 直接删掉py插件了 因为检查发现用不上 删掉就好用了
