### ISSUE TITLE
关于docekr部署的py插件相关问题

### ISSUE THREAD

**Issue by fsqhn** [SirlyDreamer/Yunzai-Bot#33]
佬，我又来了。想装个[nonebot-plugin-gspanel](https://gitee.com/work-for-myself/nonebot-plugin-gspanel)用于队伍伤害查询等功能。经查询理论上可以用py插件直接用指令#py下载插件nonebot-plugin-gspanel，直接安装。但机器人提示找不到该插件，后续发现本地插件内的[config_default.yaml]文件与py插件的仓库(https://github.com/realhuhu/py-plugin)中的并不一致。想问问这种情况该如何安装第三方py插件？

能否通过把docker源从扩展镜像改为精简镜像的方式，然后重新本地安装ffmpeg和python并更新py插件的方式处理？或者是否有更优雅便捷的方式解决这个问题。

**Comment by SirlyDreamer** [comment]
py-plugin最近做了重构，之前安装的py插件是不能直接平滑升级到新版哦。您需要在plugin文件夹里删除py-plugin然后重新`git clone`安装py插件（之前的表情制作等插件在新版貌似不可用）

**Comment by SirlyDreamer** [comment]
咱就是说宵鸟大佬本来可以把名字换成nonebot-plugin的（小声）

**Comment by fsqhn** [comment]
按大佬您的说法在plugin文件夹里删除py-plugin然后重新git clone安装py插件（这部分不是在docker内进行的），然后运行docker却提示缺依赖，在进入docker内把依赖都安装完后却启动失败了，直接显示
yunzai-bot    | Traceback (most recent call last):
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/main.py", line 4, in <module>
yunzai-bot    |     import nonebot
yunzai-bot    |   File "/app/Yunzai-Bot/plugins/py-plugin/nonebot/__init__.py", line 4, in <module>
yunzai-bot    |     from omegaconf import OmegaConf
yunzai-bot    | ModuleNotFoundError: No module named 'omegaconf'
yunzai-bot    | [YzBot][20:54:56.050][WARN] python服务器已关闭

已经试过在docker内运行了一次pip install omegaconf，但还是报这个错。这该咋整啊。

**Comment by SirlyDreamer** [comment]
进入容器删掉`~/.ovo/py.ok`，然后重启容器，这样会使得启动脚本安装py插件的依赖。你也可以直接`docker compose down`删除容器然后重新`docker compose up -d`重新创建容器。

**Comment by fsqhn** [comment]
在进入docker内部/app/Yunzai-Bot/plugins/py-plugin进行了一次poetry run pip install -r requirements.txt --trusted-host mirrors.aliyun.com 后重启云崽，倒是能成功启动了。
不过貌似新版py插件正在写帮助，发#py帮助 只是回复正在写，然后用#py下载插件nonebot-plugin-gspanel 指令，就提示正在下载后提示出错了：

出错了:Command failed: poetry run pip install nonebot-plugin-gspanel
ERROR: Exception:
Traceback (most recent call last):
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 435, in _error_catcher
    yield
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.9/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/lib/python3.9/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 538, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/app/Yunzai-Bot/plugins/py-plugin/.venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip


所以这又是咋整啊，还是说不归大佬您管了，我需要去py插件那边写issues？

**Comment by SirlyDreamer** [comment]
是网络问题哦，可以再试试

**Comment by fsqhn** [comment]
佬，我好像瞎整把py插件玩坏了。昨天后来按您之前的说法用docker compose down删除容器然后重新docker compose up -d重新创建容器。然后就出问题了，他显示更新py-插件依赖的时候会跳出如下提示

`
山上的小丘:
MTTDMLZZZK5N

山上的小丘:
unzai-bot    |  ================ 
yunzai-bot    |  [信息]  更新 py-plugin 运行依赖  
yunzai-bot    |  ================ 
yunzai-bot    | 
yunzai-bot    | Progress: resolved 0, reused 1, downloaded 0, added 0
yunzai-bot    | Progress: resolved 162, reused 162, downloaded 0, added 0
yunzai-bot    |  WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
yunzai-bot    | Progress: resolved 521, reused 520, downloaded 0, added 0
yunzai-bot    | Packages: -39
yunzai-bot    | ---------------------------------------
yunzai-bot    | 
yunzai-bot    | Progress: resolved 521, reused 520, downloaded 0, added 0, done
yunzai-bot    | Installing dependencies from lock file
yunzai-bot    | 
yunzai-bot    | No dependencies to install or update
yunzai-bot    | /app/Yunzai-Bot/plugins/py-plugin/.venv/bin/python: can't open file '/app/Yunzai-Bot/plugins/py-plugin/./install/requirements.py': [Errno 2] No such file or directory
yunzai-bot exited with code 2
`
然后就重新回到最初的拉去yunzai-bot更新…… 就一直在哪循环，根本启动不了。
后续试过再次把py插件删掉再重新git clone安装后也还是这样。
目前只能单纯的把py插件给删掉来保证机器人其他功能可以运作，但整个py插件都用不了。这又该咋搞啊QAQ

**Comment by SirlyDreamer** [comment]
使用`docker compose pull`拉取最新镜像

**Comment by fsqhn** [comment]
好的，谢谢大佬。成功解决了！已经能正常运行。
